// Unified product data structure for all categories
import { getPropertyImage } from "@/lib/property-images";
import { getVehicleImage } from "@/lib/vehicle-images";
import { CategoryType, VehicleSubcategory, PropertySubcategory } from "./categories";

// Base product interface
export interface BaseProduct {
  id: number;
  name: string;
  category: CategoryType;
  subcategory: string;
  image: string;
  location: string;
  city: string;
  marketPrice: number;
  groupPrice: number;
  savingsPercent: number;
  groupSize: number;
  spotsLeft: number;
  deadline: string;
  featured: boolean;
  shortlisted?: number;
}

// Property-specific fields
export interface PropertyProduct extends BaseProduct {
  category: "property";
  subcategory: PropertySubcategory;
  bhkOptions: string[];
  superArea: string;
  possession: string;
  isRera: boolean;
  amenities?: number;
}

// Vehicle-specific fields
export interface VehicleProduct extends BaseProduct {
  category: "vehicle";
  subcategory: VehicleSubcategory;
  brand: string;
  model: string;
  year: number;
  fuelType: "petrol" | "diesel" | "electric" | "hybrid";
  transmission: "manual" | "automatic";
  mileage?: string;
  color?: string;
  registrationYear?: number;
}

export type Product = PropertyProduct | VehicleProduct;

// Sample vehicle data (10 cars, 10 bikes)
const sampleVehicles: VehicleProduct[] = [
  // Cars
  {
    id: 1001,
    name: "Honda City 2024",
    category: "vehicle",
    subcategory: "car",
    brand: "Honda",
    model: "City",
    year: 2024,
    fuelType: "petrol",
    transmission: "automatic",
    mileage: "17.8 kmpl",
    color: "White",
    registrationYear: 2024,
    image: "/images/hero-car-1.webp",
    location: "Bodakdev",
    city: "Ahmedabad",
    marketPrice: 1500000,
    groupPrice: 1350000,
    savingsPercent: 10,
    groupSize: 10,
    spotsLeft: 3,
    deadline: "Feb 15, 2026",
    featured: true,
    shortlisted: 25,
  },
  {
    id: 1002,
    name: "Maruti Swift 2023",
    category: "vehicle",
    subcategory: "car",
    brand: "Maruti",
    model: "Swift",
    year: 2023,
    fuelType: "petrol",
    transmission: "manual",
    mileage: "23.2 kmpl",
    color: "Red",
    registrationYear: 2023,
    image: "/images/hero-car-2.webp",
    location: "Vastrapur",
    city: "Ahmedabad",
    marketPrice: 650000,
    groupPrice: 585000,
    savingsPercent: 10,
    groupSize: 15,
    spotsLeft: 5,
    deadline: "Feb 20, 2026",
    featured: false,
    shortlisted: 18,
  },
  {
    id: 1003,
    name: "Hyundai Creta 2024",
    category: "vehicle",
    subcategory: "car",
    brand: "Hyundai",
    model: "Creta",
    year: 2024,
    fuelType: "petrol",
    transmission: "automatic",
    mileage: "16.8 kmpl",
    color: "Silver",
    registrationYear: 2024,
    image: "/images/hero-car-3.webp",
    location: "SG Highway",
    city: "Ahmedabad",
    marketPrice: 1700000,
    groupPrice: 1530000,
    savingsPercent: 10,
    groupSize: 12,
    spotsLeft: 4,
    deadline: "Feb 28, 2026",
    featured: true,
    shortlisted: 32,
  },
  {
    id: 1004,
    name: "Tata Nexon EV 2024",
    category: "vehicle",
    subcategory: "car",
    brand: "Tata",
    model: "Nexon EV",
    year: 2024,
    fuelType: "electric",
    transmission: "automatic",
    mileage: "325 km range",
    color: "White",
    registrationYear: 2024,
    image: "/images/hero-car-4.webp",
    location: "Science City",
    city: "Ahmedabad",
    marketPrice: 1900000,
    groupPrice: 1710000,
    savingsPercent: 10,
    groupSize: 18,
    spotsLeft: 6,
    deadline: "Mar 10, 2026",
    featured: true,
    shortlisted: 40,
  },
  {
    id: 1005,
    name: "Kia Seltos 2023",
    category: "vehicle",
    subcategory: "car",
    brand: "Kia",
    model: "Seltos",
    year: 2023,
    fuelType: "diesel",
    transmission: "automatic",
    mileage: "19.0 kmpl",
    color: "Black",
    registrationYear: 2023,
    image: "/images/hero-car-5.webp",
    location: "Thaltej",
    city: "Ahmedabad",
    marketPrice: 1800000,
    groupPrice: 1620000,
    savingsPercent: 10,
    groupSize: 16,
    spotsLeft: 5,
    deadline: "Mar 20, 2026",
    featured: false,
    shortlisted: 27,
  },
  {
    id: 1006,
    name: "Maruti Baleno 2023",
    category: "vehicle",
    subcategory: "car",
    brand: "Maruti",
    model: "Baleno",
    year: 2023,
    fuelType: "petrol",
    transmission: "manual",
    mileage: "22.9 kmpl",
    color: "Blue",
    registrationYear: 2023,
    image: "/images/hero-car-6.webp",
    location: "Maninagar",
    city: "Ahmedabad",
    marketPrice: 900000,
    groupPrice: 810000,
    savingsPercent: 10,
    groupSize: 14,
    spotsLeft: 4,
    deadline: "Mar 25, 2026",
    featured: false,
    shortlisted: 22,
  },
  {
    id: 1007,
    name: "Toyota Hyryder Hybrid",
    category: "vehicle",
    subcategory: "car",
    brand: "Toyota",
    model: "Urban Cruiser Hyryder",
    year: 2024,
    fuelType: "hybrid",
    transmission: "automatic",
    mileage: "27.0 kmpl",
    color: "Grey",
    registrationYear: 2024,
    image: "/images/hero-car-7.webp",
    location: "Prahlad Nagar",
    city: "Ahmedabad",
    marketPrice: 2100000,
    groupPrice: 1890000,
    savingsPercent: 10,
    groupSize: 20,
    spotsLeft: 7,
    deadline: "Apr 5, 2026",
    featured: true,
    shortlisted: 38,
  },
  {
    id: 1008,
    name: "MG Hector 2023",
    category: "vehicle",
    subcategory: "car",
    brand: "MG",
    model: "Hector",
    year: 2023,
    fuelType: "petrol",
    transmission: "automatic",
    mileage: "15.0 kmpl",
    color: "White",
    registrationYear: 2023,
    image: "/images/mg-hector.png",
    location: "Navrangpura",
    city: "Ahmedabad",
    marketPrice: 2200000,
    groupPrice: 1980000,
    savingsPercent: 10,
    groupSize: 18,
    spotsLeft: 6,
    deadline: "Apr 10, 2026",
    featured: false,
    shortlisted: 30,
  },
  {
    id: 1009,
    name: "Hyundai Venue 2024",
    category: "vehicle",
    subcategory: "car",
    brand: "Hyundai",
    model: "Venue",
    year: 2024,
    fuelType: "petrol",
    transmission: "manual",
    mileage: "18.0 kmpl",
    color: "Red",
    registrationYear: 2024,
    image: "/images/hyundai-venue.png",
    location: "Gota",
    city: "Ahmedabad",
    marketPrice: 1200000,
    groupPrice: 1080000,
    savingsPercent: 10,
    groupSize: 12,
    spotsLeft: 4,
    deadline: "Apr 15, 2026",
    featured: false,
    shortlisted: 19,
  },
  {
    id: 1010,
    name: "Skoda Slavia 2023",
    category: "vehicle",
    subcategory: "car",
    brand: "Skoda",
    model: "Slavia",
    year: 2023,
    fuelType: "petrol",
    transmission: "automatic",
    mileage: "19.5 kmpl",
    color: "Grey",
    registrationYear: 2023,
    image: "/images/skoda-slavia.png",
    location: "Satellite",
    city: "Ahmedabad",
    marketPrice: 1800000,
    groupPrice: 1620000,
    savingsPercent: 10,
    groupSize: 15,
    spotsLeft: 5,
    deadline: "Apr 20, 2026",
    featured: false,
    shortlisted: 21,
  },

  // Bikes
  {
    id: 2001,
    name: "Royal Enfield Classic 350",
    category: "vehicle",
    subcategory: "bike",
    brand: "Royal Enfield",
    model: "Classic 350",
    year: 2024,
    fuelType: "petrol",
    transmission: "manual",
    mileage: "35 kmpl",
    color: "Black",
    registrationYear: 2024,
    image: "/images/re-classic-350.png",
    location: "Bopal",
    city: "Ahmedabad",
    marketPrice: 250000,
    groupPrice: 225000,
    savingsPercent: 10,
    groupSize: 20,
    spotsLeft: 8,
    deadline: "Feb 25, 2026",
    featured: true,
    shortlisted: 42,
  },
  {
    id: 2002,
    name: "Yamaha MT-15",
    category: "vehicle",
    subcategory: "bike",
    brand: "Yamaha",
    model: "MT-15",
    year: 2024,
    fuelType: "petrol",
    transmission: "manual",
    mileage: "56.8 kmpl",
    color: "Blue",
    registrationYear: 2024,
    image: "/images/yamaha-mt15.png",
    location: "Naranpura",
    city: "Ahmedabad",
    marketPrice: 180000,
    groupPrice: 162000,
    savingsPercent: 10,
    groupSize: 25,
    spotsLeft: 12,
    deadline: "Mar 1, 2026",
    featured: false,
    shortlisted: 35,
  },
  {
    id: 2003,
    name: "Honda Activa 6G",
    category: "vehicle",
    subcategory: "bike",
    brand: "Honda",
    model: "Activa 6G",
    year: 2023,
    fuelType: "petrol",
    transmission: "automatic",
    mileage: "50 kmpl",
    color: "White",
    registrationYear: 2023,
    image: "/images/honda-activa-6g.png",
    location: "Ghatlodia",
    city: "Ahmedabad",
    marketPrice: 85000,
    groupPrice: 76500,
    savingsPercent: 10,
    groupSize: 30,
    spotsLeft: 10,
    deadline: "Mar 5, 2026",
    featured: true,
    shortlisted: 48,
  },
  {
    id: 2004,
    name: "TVS Jupiter",
    category: "vehicle",
    subcategory: "bike",
    brand: "TVS",
    model: "Jupiter",
    year: 2023,
    fuelType: "petrol",
    transmission: "automatic",
    mileage: "55 kmpl",
    color: "Grey",
    registrationYear: 2023,
    image: "/images/tvs-jupiter.png",
    location: "Nikol",
    city: "Ahmedabad",
    marketPrice: 90000,
    groupPrice: 81000,
    savingsPercent: 10,
    groupSize: 24,
    spotsLeft: 9,
    deadline: "Mar 10, 2026",
    featured: false,
    shortlisted: 29,
  },
  {
    id: 2005,
    name: "Bajaj Pulsar 150",
    category: "vehicle",
    subcategory: "bike",
    brand: "Bajaj",
    model: "Pulsar 150",
    year: 2024,
    fuelType: "petrol",
    transmission: "manual",
    mileage: "47 kmpl",
    color: "Black",
    registrationYear: 2024,
    image: getVehicleImage("bike", 4),
    location: "Chandkheda",
    city: "Ahmedabad",
    marketPrice: 125000,
    groupPrice: 112500,
    savingsPercent: 10,
    groupSize: 22,
    spotsLeft: 7,
    deadline: "Mar 15, 2026",
    featured: false,
    shortlisted: 33,
  },
  {
    id: 2006,
    name: "Suzuki Access 125",
    category: "vehicle",
    subcategory: "bike",
    brand: "Suzuki",
    model: "Access 125",
    year: 2023,
    fuelType: "petrol",
    transmission: "automatic",
    mileage: "52 kmpl",
    color: "Silver",
    registrationYear: 2023,
    image: getVehicleImage("bike", 5),
    location: "Ellis Bridge",
    city: "Ahmedabad",
    marketPrice: 105000,
    groupPrice: 94500,
    savingsPercent: 10,
    groupSize: 26,
    spotsLeft: 9,
    deadline: "Mar 20, 2026",
    featured: true,
    shortlisted: 36,
  },
  {
    id: 2007,
    name: "KTM Duke 250",
    category: "vehicle",
    subcategory: "bike",
    brand: "KTM",
    model: "Duke 250",
    year: 2024,
    fuelType: "petrol",
    transmission: "manual",
    mileage: "30 kmpl",
    color: "Orange",
    registrationYear: 2024,
    image: getVehicleImage("bike", 6),
    location: "Drive-In Road",
    city: "Ahmedabad",
    marketPrice: 250000,
    groupPrice: 225000,
    savingsPercent: 10,
    groupSize: 18,
    spotsLeft: 6,
    deadline: "Mar 25, 2026",
    featured: true,
    shortlisted: 41,
  },
  {
    id: 2008,
    name: "Hero Splendor Plus",
    category: "vehicle",
    subcategory: "bike",
    brand: "Hero",
    model: "Splendor Plus",
    year: 2023,
    fuelType: "petrol",
    transmission: "manual",
    mileage: "65 kmpl",
    color: "Black",
    registrationYear: 2023,
    image: "/images/hero-splendor-plus.png",
    location: "Naroda",
    city: "Ahmedabad",
    marketPrice: 80000,
    groupPrice: 72000,
    savingsPercent: 10,
    groupSize: 28,
    spotsLeft: 11,
    deadline: "Mar 30, 2026",
    featured: false,
    shortlisted: 24,
  },
  {
    id: 2009,
    name: "Ather 450X",
    category: "vehicle",
    subcategory: "bike",
    brand: "Ather",
    model: "450X",
    year: 2024,
    fuelType: "electric",
    transmission: "automatic",
    mileage: "146 km range",
    color: "White",
    registrationYear: 2024,
    image: "/images/ather-450x.png",
    location: "Ambli",
    city: "Ahmedabad",
    marketPrice: 160000,
    groupPrice: 144000,
    savingsPercent: 10,
    groupSize: 20,
    spotsLeft: 7,
    deadline: "Apr 5, 2026",
    featured: true,
    shortlisted: 39,
  },
  {
    id: 2010,
    name: "Ola S1 Pro",
    category: "vehicle",
    subcategory: "bike",
    brand: "Ola Electric",
    model: "S1 Pro",
    year: 2024,
    fuelType: "electric",
    transmission: "automatic",
    mileage: "181 km range",
    color: "Red",
    registrationYear: 2024,
    image: "/images/ola-s1-pro.png",
    location: "Sindhu Bhavan Road",
    city: "Ahmedabad",
    marketPrice: 170000,
    groupPrice: 153000,
    savingsPercent: 10,
    groupSize: 22,
    spotsLeft: 8,
    deadline: "Apr 10, 2026",
    featured: false,
    shortlisted: 34,
  },
  {
    id: 2011,
    name: "Hero Electric Dash",
    category: "vehicle",
    subcategory: "bike",
    brand: "Hero Electric",
    model: "Dash",
    year: 2023,
    fuelType: "electric",
    transmission: "automatic",
    mileage: "60 km range",
    color: "White",
    registrationYear: 2023,
    image: "/images/electric-scooter-1.png",
    location: "Ashram Road",
    city: "Ahmedabad",
    marketPrice: 130000,
    groupPrice: 117000,
    savingsPercent: 10,
    groupSize: 20,
    spotsLeft: 9,
    deadline: "Apr 15, 2026",
    featured: false,
    shortlisted: 20,
  },
];

// Import existing properties and convert to new structure
import { ALL_PROPERTIES as OLD_PROPERTIES, Property as OldProperty } from "./properties-data";

function convertPropertyToProduct(oldProp: OldProperty): PropertyProduct {
  return {
    id: oldProp.id,
    name: oldProp.name,
    category: "property",
    subcategory: "apartment", // Default, can be enhanced
    image: oldProp.image,
    location: oldProp.location,
    city: oldProp.city,
    bhkOptions: oldProp.bhkOptions,
    superArea: oldProp.superArea,
    groupSize: oldProp.groupSize,
    spotsLeft: oldProp.spotsLeft,
    deadline: oldProp.deadline,
    marketPrice: oldProp.marketPrice,
    groupPrice: oldProp.groupPrice,
    savingsPercent: oldProp.savingsPercent,
    possession: oldProp.possession,
    isRera: oldProp.isRera,
    featured: oldProp.featured,
    amenities: 20, // Default
    shortlisted: 0,
  };
}

// All products (properties + vehicles)
export const ALL_PRODUCTS: Product[] = [
  ...OLD_PROPERTIES.map(convertPropertyToProduct),
  ...sampleVehicles,
];

// Helper functions
export function getProductsByCategory(category: CategoryType): Product[] {
  return ALL_PRODUCTS.filter((p) => p.category === category);
}

export function getProductsBySubcategory(
  category: CategoryType,
  subcategory: string
): Product[] {
  return ALL_PRODUCTS.filter(
    (p) => p.category === category && p.subcategory === subcategory
  );
}

export function getProductById(id: number): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export function getProductSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

// Type guards
export function isPropertyProduct(product: Product): product is PropertyProduct {
  return product.category === "property";
}

export function isVehicleProduct(product: Product): product is VehicleProduct {
  return product.category === "vehicle";
}
