import { getPropertyImage } from "@/lib/property-images";

export interface Property {
  id: number;
  name: string;
  location: string;
  city: string;
  image: string;
  bhkOptions: string[];
  superArea: string;
  groupSize: number;
  spotsLeft: number;
  deadline: string;
  marketPrice: number;
  groupPrice: number;
  savingsPercent: number;
  possession: string;
  isRera: boolean;
  featured: boolean;
}

export const ALL_PROPERTIES: Property[] = [
  {
    id: 1,
    name: "Adani Shantigram",
    location: "Bopal",
    city: "Ahmedabad",
    image: "/images/adani-shantigram.png",
    bhkOptions: ["2 BHK", "3 BHK", "4 BHK"],
    superArea: "1,245 - 2,890 sq.ft.",
    groupSize: 5,
    spotsLeft: 0,
    deadline: "31st Jan, 26",
    marketPrice: 105000000,
    groupPrice: 95000000,
    savingsPercent: 10,
    possession: "Dec 2027",
    isRera: true,
    featured: true,
  },
  {
    id: 2,
    name: "Godrej Garden City",
    location: "SG Highway",
    city: "Ahmedabad",
    image: getPropertyImage(1),
    bhkOptions: ["3 BHK", "4 BHK"],
    superArea: "2,100 - 3,450 sq.ft.",
    groupSize: 4,
    spotsLeft: 2,
    deadline: "31st Jan, 26",
    marketPrice: 59800000,
    groupPrice: 55000000,
    savingsPercent: 8,
    possession: "Mar 2028",
    isRera: true,
    featured: false,
  },
  {
    id: 3,
    name: "Torrent Group Projects",
    location: "Bodakdev",
    city: "Ahmedabad",
    image: getPropertyImage(2),
    bhkOptions: ["2 BHK", "3 BHK", "4 BHK"],
    superArea: "1,245 - 2,890 sq.ft.",
    groupSize: 15,
    spotsLeft: 3,
    deadline: "Jan 31, 2026",
    marketPrice: 18500000,
    groupPrice: 15200000,
    savingsPercent: 18,
    possession: "Dec 2027",
    isRera: true,
    featured: true,
  },
  {
    id: 4,
    name: "Artha Infra",
    location: "Satellite",
    city: "Ahmedabad",
    image: getPropertyImage(3),
    bhkOptions: ["3 BHK", "4 BHK"],
    superArea: "2,100 - 3,450 sq.ft.",
    groupSize: 20,
    spotsLeft: 7,
    deadline: "Feb 15, 2026",
    marketPrice: 42000000,
    groupPrice: 35500000,
    savingsPercent: 15,
    possession: "Mar 2028",
    isRera: true,
    featured: true,
  },
  {
    id: 5,
    name: "Siddhi Vinayak",
    location: "Prahlad Nagar",
    city: "Ahmedabad",
    image: getPropertyImage(4),
    bhkOptions: ["1 BHK", "2 BHK", "3 BHK"],
    superArea: "650 - 1,450 sq.ft.",
    groupSize: 25,
    spotsLeft: 12,
    deadline: "Feb 28, 2026",
    marketPrice: 9500000,
    groupPrice: 7800000,
    savingsPercent: 18,
    possession: "Jun 2027",
    isRera: true,
    featured: false,
  },
  {
    id: 6,
    name: "Shivalik Group",
    location: "Thaltej",
    city: "Ahmedabad",
    image: getPropertyImage(5),
    bhkOptions: ["3 BHK", "4 BHK"],
    superArea: "1,890 - 2,650 sq.ft.",
    groupSize: 12,
    spotsLeft: 2,
    deadline: "Jan 25, 2026",
    marketPrice: 32000000,
    groupPrice: 26500000,
    savingsPercent: 17,
    possession: "Sep 2027",
    isRera: true,
    featured: false,
  },
  {
    id: 7,
    name: "The Address",
    location: "Maninagar",
    city: "Ahmedabad",
    image: getPropertyImage(6),
    bhkOptions: ["2 BHK", "3 BHK"],
    superArea: "1,120 - 1,890 sq.ft.",
    groupSize: 18,
    spotsLeft: 5,
    deadline: "Mar 10, 2026",
    marketPrice: 14500000,
    groupPrice: 11900000,
    savingsPercent: 18,
    possession: "Dec 2028",
    isRera: true,
    featured: false,
  },
  {
    id: 8,
    name: "Ashapura Group",
    location: "Gota",
    city: "Ahmedabad",
    image: getPropertyImage(7),
    bhkOptions: ["2 BHK", "3 BHK", "4 BHK"],
    superArea: "1,450 - 2,980 sq.ft.",
    groupSize: 16,
    spotsLeft: 4,
    deadline: "Feb 5, 2026",
    marketPrice: 28000000,
    groupPrice: 23500000,
    savingsPercent: 16,
    possession: "Mar 2027",
    isRera: true,
    featured: true,
  },
  {
    id: 9,
    name: "Safal Group",
    location: "Vastrapur",
    city: "Ahmedabad",
    image: getPropertyImage(8),
    bhkOptions: ["2 BHK", "3 BHK"],
    superArea: "1,350 - 2,100 sq.ft.",
    groupSize: 14,
    spotsLeft: 6,
    deadline: "Mar 20, 2026",
    marketPrice: 22000000,
    groupPrice: 18500000,
    savingsPercent: 16,
    possession: "Sep 2028",
    isRera: true,
    featured: false,
  },
  {
    id: 10,
    name: "Nilkanth Group",
    location: "Naroda",
    city: "Ahmedabad",
    image: getPropertyImage(9),
    bhkOptions: ["2 BHK", "3 BHK", "4 BHK"],
    superArea: "1,200 - 2,500 sq.ft.",
    groupSize: 22,
    spotsLeft: 8,
    deadline: "Feb 28, 2026",
    marketPrice: 16500000,
    groupPrice: 13800000,
    savingsPercent: 16,
    possession: "Jun 2028",
    isRera: true,
    featured: false,
  },
  {
    id: 11,
    name: "Savvy Group",
    location: "Science City",
    city: "Ahmedabad",
    image: getPropertyImage(10),
    bhkOptions: ["3 BHK", "4 BHK"],
    superArea: "1,950 - 3,200 sq.ft.",
    groupSize: 10,
    spotsLeft: 1,
    deadline: "Jan 20, 2026",
    marketPrice: 48000000,
    groupPrice: 40500000,
    savingsPercent: 16,
    possession: "Dec 2027",
    isRera: true,
    featured: true,
  },
  {
    id: 12,
    name: "Manav Group",
    location: "Vejalpur",
    city: "Ahmedabad",
    image: getPropertyImage(11),
    bhkOptions: ["2 BHK", "3 BHK"],
    superArea: "1,400 - 2,200 sq.ft.",
    groupSize: 18,
    spotsLeft: 5,
    deadline: "Mar 15, 2026",
    marketPrice: 28000000,
    groupPrice: 23500000,
    savingsPercent: 16,
    possession: "Jun 2028",
    isRera: true,
    featured: false,
  },
  {
    id: 13,
    name: "Panchshil Group",
    location: "Ambli",
    city: "Ahmedabad",
    image: getPropertyImage(12),
    bhkOptions: ["2 BHK", "3 BHK", "4 BHK"],
    superArea: "1,180 - 2,400 sq.ft.",
    groupSize: 20,
    spotsLeft: 7,
    deadline: "Feb 20, 2026",
    marketPrice: 12500000,
    groupPrice: 10200000,
    savingsPercent: 18,
    possession: "Mar 2028",
    isRera: true,
    featured: false,
  },
  {
    id: 14,
    name: "Rajhans Group",
    location: "Memnagar",
    city: "Ahmedabad",
    image: getPropertyImage(13),
    bhkOptions: ["3 BHK", "4 BHK"],
    superArea: "2,050 - 3,500 sq.ft.",
    groupSize: 12,
    spotsLeft: 3,
    deadline: "Jan 30, 2026",
    marketPrice: 55000000,
    groupPrice: 47200000,
    savingsPercent: 14,
    possession: "Sep 2028",
    isRera: true,
    featured: true,
  },
];

export function getPropertySlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

